### ISSUE TITLE
Woocommerce pages error - Instagram Feed Pro

### ISSUE THREAD

**Issue by jchrislemmer** [smashballoon/instagram-feed#21]
Hi there,

When I use the module on a Woocommerce page, I get the following error:

sb-instagram.js?ver=2.8.1:997 Uncaught TypeError: Cannot read property 'includewords' of null
    at HTMLDivElement.<anonymous> (sb-instagram.js?ver=2.8.1:997)
    at Function.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.each (jquery.js?ver=1.12.4:2)
    at sb-instagram.js?ver=2.8.1:995
    at sbiCreatePage (sb-instagram.js?ver=2.8.1:1011)
    at sbi_init (sb-instagram.js?ver=2.8.1:992)
    at HTMLDocument.<anonymous> (sb-instagram.js?ver=2.8.1:2882)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:2)
    at Function.ready (jquery.js?ver=1.12.4:2)

  | (anonymous) | @ | sb-instagram.js?ver=2.8.1:997
-- | -- | -- | --
  | each | @ | jquery.js?ver=1.12.4:2
  | each | @ | jquery.js?ver=1.12.4:2
  | (anonymous) | @ | sb-instagram.js?ver=2.8.1:995
  | sbiCreatePage | @ | sb-instagram.js?ver=2.8.1:1011
  | sbi_init | @ | sb-instagram.js?ver=2.8.1:992
  | (anonymous) | @ | sb-instagram.js?ver=2.8.1:2882
  | i | @ | jquery.js?ver=1.12.4:2
  | fireWith | @ | jquery.js?ver=1.12.4:2
  | ready | @ | jquery.js?ver=1.12.4:2
  | K | @ | jquery.js?ver=1.12.4:2

It only happens on Woocommerce pages. On all other pages, it works. You can view this page to check - https://uat.themattresswarehouse.co.za/ If you get a block, just let me know then I will allow GEO access.

Thanks
Chris

**Comment by jchrislemmer** [comment]
Btw, the actual error is in this line:

**Line 997 (sb-instagram.js): Uncaught TypeError: Cannot read property 'includewords' of null**

        var $i = 0, //Used for iterating lightbox
            sbi_time = 0, //might be added to if includewords is used on the page
            numIncludewords = 0; //keep track of includewords feeds on page

        sbiCreatePage( function() {
            // using this code as the callback to make sure we know if includewords is being used
            // and we need to stagger the loading of the feeds
            jQuery('#sb_instagram.sbi').each(function () {
                var feedOptions = JSON.parse( this.getAttribute('data-options') );
                **_if (feedOptions.includewords.length > 0) {_**
                    numIncludewords++;
                }
                if (feedOptions.lightboxcomments == 'true' && window.sbiCommentCacheStatus !== 1 && feedOptions.numcomments > 0) {
                    window.sbiCommentCacheStatus = 1;
                }
            });

        });

**Comment by craigschlegel** [comment]
Caused by WooCommerce's use of wp_kses_post() on the product archive description. https://github.com/woocommerce/woocommerce/pull/17499/files?diff=split

To fix the issue.
 
Edit file in WooCommerce (they will include this in a future release):
 
includes/wc-template-functions.php:696
 
 
    /**
    * Show a shop page description on product archives.
    *
    * @subpackage Archives
    */
   function woocommerce_product_archive_description() {
      // Don't display the description on search results page.
      if ( is_search() ) {
         return;
      }

      if ( is_post_type_archive( 'product' ) && 0 === absint( get_query_var( 'paged' ) ) ) {
         $shop_page = get_post( wc_get_page_id( 'shop' ) );
         if ( $shop_page ) {
            $description = wc_format_content( $shop_page->post_content );
            if ( $description ) {
               echo '<div class="page-description">' . $description . '</div>'; // WPCS: XSS ok.
            }
         }
      }
   }
}
